"""initial_schema

Revision ID: c48ad7126f03
Revises: 
Create Date: 2026-09-19 19:19:34.425281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c48ad7126f03'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('assessment', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_strength', sa.String(length=20), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_analyses'))
    )
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analyses_assessment'), ['assessment'], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_analyses_created_at_desc', [sa.literal_column('created_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_analyses_language'), ['language'], unique=False)

    op.create_table('claims',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('analysis_id', sa.String(length=12), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_claim', sa.Text(), nullable=True),
    sa.Column('claim_type', sa.String(length=50), nullable=True),
    sa.Column('entities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_claims_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claims'))
    )
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_claims_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('model_runs',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('analysis_id', sa.String(length=12), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('prediction', sa.Text(), nullable=True),
    sa.Column('probabilities', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_model_runs_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_model_runs'))
    )
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_runs_analysis_id'), ['analysis_id'], unique=False)

    op.create_table('pipeline_events',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('analysis_id', sa.String(length=12), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], name=op.f('fk_pipeline_events_analysis_id_analyses'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline_events'))
    )
    with op.batch_alter_table('pipeline_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pipeline_events_analysis_id'), ['analysis_id'], unique=False)
        batch_op.create_index('ix_pipeline_events_analysis_id_timestamp', ['analysis_id', 'timestamp'], unique=False)

    op.create_table('evidence',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('claim_id', sa.String(length=12), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('relation', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], name=op.f('fk_evidence_claim_id_claims'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evidence_claim_id'), ['claim_id'], unique=False)
        batch_op.create_index('ix_evidence_claim_id_relation', ['claim_id', 'relation'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evidence', schema=None) as batch_op:
        batch_op.drop_index('ix_evidence_claim_id_relation')
        batch_op.drop_index(batch_op.f('ix_evidence_claim_id'))

    op.drop_table('evidence')
    with op.batch_alter_table('pipeline_events', schema=None) as batch_op:
        batch_op.drop_index('ix_pipeline_events_analysis_id_timestamp')
        batch_op.drop_index(batch_op.f('ix_pipeline_events_analysis_id'))

    op.drop_table('pipeline_events')
    with op.batch_alter_table('model_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_runs_analysis_id'))

    op.drop_table('model_runs')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_claims_analysis_id'))

    op.drop_table('claims')
    with op.batch_alter_table('analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analyses_language'))
        batch_op.drop_index('ix_analyses_created_at_desc')
        batch_op.drop_index(batch_op.f('ix_analyses_created_at'))
        batch_op.drop_index(batch_op.f('ix_analyses_assessment'))

    op.drop_table('analyses')
    # ### end Alembic commands ###
